[project]
name = "creature-racer"
authors = []
description = ""
telemetry = false
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[project.cache_location]
path = ".requirements"
[contracts.creature-racer-payment]
path = "contracts/creature-racer-payment.clar"

[contracts.creature-racer-referral-nft]
path = "contracts/creature-racer-referral-nft.clar"

[contracts.creature-racer-referral-pool]
path = "contracts/creature-racer-referral-pool.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
