[project]
name = 'creature-racer'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'
[contracts.creature-racer-admin-v3]
path = 'contracts/creature-racer-admin.clar'
clarity_version = 1

[contracts.creature-racer-nft-v3]
path = 'contracts/creature-racer-nft.clar'
clarity_version = 1

[contracts.creature-racer-payment-v3]
path = 'contracts/creature-racer-payment.clar'
clarity_version = 1

[contracts.creature-racer-referral-nft-v3]
path = 'contracts/creature-racer-referral-nft.clar'
clarity_version = 1

[contracts.creature-racer-referral-pool-v3]
path = 'contracts/creature-racer-referral-pool.clar'
clarity_version = 1

[contracts.creature-racer-reward-pool-v3]
path = 'contracts/creature-racer-reward-pool.clar'
clarity_version = 1

[contracts.creature-racer-staking-v3]
path = 'contracts/creature-racer-staking.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
